language: ruby
dist: trusty
sudo: false
cache: bundler
rvm:
  - 2.3.1
addons:
  apt:
    packages:
      - vim-gtk
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "vim --version"
